### PR TITLE
Added openshift-conformance role

### PR DESCRIPTION
**Pull request by e-minguez**
Added openshift-conformance role based on the test suites. Also included the current how-to in the README file.

### CODE REVIEW

**Comment by joeldavis84** [comment]
Basically the part where it fails to create a role due to not having the permissions to give out is a known issue with the audit2role script. I was in the process of trying to find a way to programmatically determine what privileges were requested when I started PTO. Basically my MO for that one was:

1. Switch to the restricted role
2. Run the test suite again, letting the role creation fail
3. Copy/Paste the nearly-JSON portions of the error output in the junit results into a flat file on my desktop/the server.
4. Use the regexp in vim to make sure the JSON keys are surrounded by double quotes and that the elements in the verbs list are separated by commas.

This is enough to ensure the JSON can be parsed by python and I have a python script for taking the JSON and converting it into the apiRule YAML that I append to the end of the custom role. This part isn't really that difficult and I can shared the 5-10 line python script I was using to do this if you want.

This is obviously pretty kludgey but it got the other two to where they work for me and I was going to try to figure out how to enumerate what privileges where requested for the new role when I got back (post-CNV). The end result hopefully being that just running the test suite once with cluster-admin privileges should be enough for the script to figure it out. Until I figure that part out they're separate processes though.

I was also re-deploying the cluster to clean the API logs out in between role creations.

**Comment by e-minguez** [comment]
> Basically the part where it fails to create a role due to not having the permissions to give out is a known issue with the audit2role script. I was in the process of trying to find a way to programmatically determine what privileges were requested when I started PTO. Basically my MO for that one was:
> 
>     1. Switch to the restricted role
> 
>     2. Run the test suite again, letting the role creation fail
> 
>     3. Copy/Paste the nearly-JSON portions of the error output in the junit results into a flat file on my desktop/the server.
> 
>     4. Use the regexp in vim to make sure the JSON keys are surrounded by double quotes and that the elements in the verbs list are separated by commas.
> 
> 
> This is enough to ensure the JSON can be parsed by python and I have a python script for taking the JSON and converting it into the apiRule YAML that I append to the end of the custom role. This part isn't really that difficult and I can shared the 5-10 line python script I was using to do this if you want.
> 

Please do :D I thought it was easier but I've seen a lot of missing rules (like A LOT)... so if you have the regexp and all that stuff already there it would be easier.

> This is obviously pretty kludgey but it got the other two to where they work for me and I was going to try to figure out how to enumerate what privileges where requested for the new role when I got back (post-CNV). The end result hopefully being that just running the test suite once with cluster-admin privileges should be enough for the script to figure it out. Until I figure that part out they're separate processes though.
> 

It is ok if is not polished but if you can share those with me I will add it to the repo because otherwise the audit2role is otherwise incomplete I'm afraid.

> I was also re-deploying the cluster to clean the API logs out in between role creations.

I'm validating the roles already created in this PR using your instructions, so far:

Validated:
* osetests-openshift-network-stress.yaml

Not tested:
* osetests-all-disruptive.yaml
* osetests-all-non-disruptive.yaml
* osetests-openshift-conformance-excluded-disruptive.yaml
* osetests-openshift-conformance-excluded-non-disruptive.yaml
* osetests-openshift-conformance.yaml

[I will modify this after validating each one of those]

**Comment by e-minguez** [comment]
@joeldavis84 please correct me if I'm wrong. The whole process would be:

- Create a fresh cluster
- Create a tests user with cluster-admin permissions
- Run the test-suite as documented here
- Run the audit2role script with -n and -o set

This will generate the clusterrole but it misses some stuff. To fix it, it is required to perform some work:

- Apply the clusterrole to the user and remove the cluster-admin permissions
- Run the tests again

Some tests will fail because of permissions.

- Create a file with the content of each of the failed tests output from the html junit output (`foo.json`), as:
```
{APIGroups:[""], Resources:["processedtemplates"], Verbs:["create" "delete" "deletecollection" "get" "list" "patch" "update" "watch" "get" "list" "watch"]}
    {APIGroups:[""], Resources:["projects"], Verbs:["get"]}
    {APIGroups:[""], Resources:["replicationcontrollers"], Verbs:["deletecollection" "patch" "update" "watch"]}
    {APIGroups:[""], Resources:["replicationcontrollers/scale"], Verbs:["create" "delete" "deletecollection" "patch" "update" "get" "list" "watch"]}
    {APIGroups:[""], Resources:["replicationcontrollers/status"], Verbs:["get" "list" "watch"]}
    {APIGroups:[""], Resources:["resourcequotas"], Verbs:["get" "watch"]}
...
```

- Convert that file to json:

```
sed -i -e 's/APIGroups:/"APIGroups":/g' -e 's/Resources:/"Resources":/g' -e 's/Verbs:/"Verbs":/g' -e 's/" "/","/g' foo.json
```

- Create the following helper script:

```
#!/usr/bin/python3
 
import json,sys
 
with open(sys.argv[1]) as fh: 
    for line in fh.readlines():
        jsonObject=json.loads(line) 
        print("- apiGroups:")
        print("- "+ jsonObject['APIGroups'][0])
        print("resources:")
        print("- "+ jsonObject['Resources'][0])
        print("verbs:")
        for verb in jsonObject['Verbs']: 
            print("- "+ verb)
```

Then, run it as:

```
python foo.py foo.json
```

- Append the output to the clusterrole previously created.

- Verify it works.

**Comment by joeldavis84** [comment]
That is correct although for clarity I still think of this process as a workaround because I consider being able to enumerate the rights granted to a user would be require for audit2role to be a "minimally viable product." I'm just in the process of figuring out where this information might be stored.

**Pull request merged**
